### PR TITLE
add file hash to STAC metadata

### PR DESCRIPTION
**Pull request by johntruckenbrodt**
This computes the SHA256 hash for all assets and adds it as attribute `file:checksum` to the metadata.

### CODE REVIEW

**Comment by jonas-eberle** [comment]
@johntruckenbrodt Thanks. Is there a property in STAC that defines the algorithm used to calculate the checksum (here SHA256)?

**Comment by johntruckenbrodt** [comment]
Hi @jonas-eberle, good point. The STAC file extension details the `file:checksum` attribute as:
> Provides a way to specify file [checksums](https://github.com/stac-extensions/file#checksums) (e.g. BLAKE2, MD5, SHA1, SHA2, SHA3). The hashes are self-identifying hashes as described in the [Multihash specification](https://github.com/multiformats/multihash) and must be encoded as hexadecimal (base 16) string with lowercase letters.

The `multihash` hashes have a unique prefix per algorithm:
https://github.com/multiformats/multihash?tab=readme-ov-file#idea-self-describe-the-values-to-distinguish

Looks like I need to encode the hash using `multihash`.

**Comment by johntruckenbrodt** [comment]
Okay the latest commit fixes it.  
For the protocol: the relevant `multihash` function cannot properly be referenced in the documentation (see https://github.com/hashberg-io/multiformats/issues/21).

**Comment by johntruckenbrodt** [comment]
https://github.com/hashberg-io/multiformats/issues/21 has been fixed and documentation is done.

**Pull request merged**
